### ISSUE TITLE
@Dreeam-qwq我爱死你了

### ISSUE THREAD

**Issue by Choneas** [KeYiMC/KeYi#2]
@Dreeam-qwq 我爱死你了呜呜呜 快关掉这个Issue

**Comment by Choneas** [comment]
顺便说一句 这个如何使用 是服务端还是插件

**Comment by Choneas** [comment]
自述文件 **新手无法理解**

**Comment by Dreeam-qwq** [comment]
是服务端核心，基于Purpur核心，使用方法和常用核心(paper, spigot等)一样

**Comment by Choneas** [comment]
Purpur确实是个好东西 但是purpur很多功能我用不到 插件也能解决😘

________________________________
发件人: Dreeam ***@***.***>
发送时间: Friday, November 18, 2022 8:18:03 PM
收件人: KeYiMC/KeYi ***@***.***>
抄送: Chenken520 ***@***.***>; Author ***@***.***>
主题: Re: [KeYiMC/KeYi] @Dreeam-qwq我爱死你了 (Issue #2)


是服务端核心，基于Purpur核心，使用方法和常用核心(paper, spigot等)一样
