### ISSUE TITLE
[BUG]不兼容TrChat及TrMenu

### ISSUE THREAD

**Issue by YunDouYue** [KeYiMC/KeYi#7]
KeYi端版本：1.19.3#8
[https://github.com/KeYiMC/KeYi/releases/download/main-1.19.3/keyi-main-1.19.3-8.jar](https://github.com/KeYiMC/KeYi/releases/download/main-1.19.3/keyi-main-1.19.3-8.jar)
TrChat最新构建项名：[2.0.0-RC-7] Update & Fix #219既Actions最新版
[https://github.com/TrPlugins/TrChat/actions/runs/3917949236](https://github.com/TrPlugins/TrChat/actions/runs/3917949236)
TrMenu最新构建项名：Merge pull request #394 from Rubenicos/v3 #85既Actions最新版
[https://github.com/InsinuateProjects/TrMenu/actions/runs/3786428510](https://github.com/InsinuateProjects/TrMenu/actions/runs/3786428510)

复现方式：直接用KeYi1.19.3#8端启动且在plugins内安装TrChat-2.0.0-RC7、TrMenu-3.1.17、PlaceholderAPI-2.11.2
测试端插件列表[使用的插件均为构建最新版]：PlaceholderAPI、PlugManX、ProtocolLib、TrChat、TrMenu、Vault
未对服务端任何文件进行更改
完整日志：[https://paste.ubuntu.com/p/NzChNjB8mF/](https://paste.ubuntu.com/p/NzChNjB8mF/)
个人想法：KeYi端在1.19.2时可以正常使用TrChat、TrMenu两个插件，可能是由于TabooLib[https://github.com/TabooLib/taboolib](https://github.com/TabooLib/taboolib)版本更新至6.0.10，同样的在Arclight[https://github.com/IzzelAliz/Arclight](https://github.com/IzzelAliz/Arclight)端中也出现了类似问题、Arclight端发布在TabooLib的issue[https://github.com/TabooLib/taboolib/issues/281](https://github.com/TabooLib/taboolib/issues/281)
本人使用purpur-1.19.3-1894后开启服务器并且安装TrChat、TrMenu可以正常使用

**Comment by xiaozhangup** [comment]
怎么是文本解析的问题，你可以发给黑哥看看

**Comment by nostalgic853** [comment]
是否确认过是编码问题？KeYi 不会影响文本解析的部分。
